version: '3.8'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rootuser
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
      ME_CONFIG_MONGODB_URL: "mongodb://rootuser:rootpass@mongo:27017/"
    ports:
      - "8282:8081"

volumes:
  mongo-data: